name-template: 'v$NEXT_PATCH_VERSION 🌟'
tag-template: 'v$NEXT_PATCH_VERSION'
categories:
  - title: '🚀 Features'
    labels:
      - 'feat'
      - 'feature'
  - title: '🐞 Bug Fixes'
    labels:
      - 'fix'
      - 'bug'
  - title: '🛠 Maintenance'
    labels:
      - 'chore'
      - 'docs'
      - 'refactor'
change-template: '- $TITLE @$AUTHOR (#$NUMBER)'
change-title-escapes: '\"'
version-resolver:
  major:
    labels:
      - 'major'
  minor:
    labels:
      - 'minor'
  patch:
    labels:
      - 'patch'
      - 'bug'
      - 'fix'
  default: patch
template: |
  ## Changes

  $CHANGES

  ## Contributors

  $CONTRIBUTORS
