---
name: General Discussion 💬
about: Start a conversation or share feedback not covered by other templates
title: "[DISCUSSION] "
labels: discussion
---

## Topic
What would you like to discuss?

## Details
Provide more context or background.

## Suggestions
How do you think we should move forward?
