---
name: Idea 💡
about: Share an idea to improve the action
title: "[IDEA] "
labels: enhancement
---

## Idea
Describe your idea.

## Motivation
Why is this valuable? What problem does it solve?

## Implementation thoughts
Optional: how might this be implemented?
