---
name: Question 🙋
about: Ask a question about using or configuring the action
title: "[Q&A] "
labels: question
---

## Question
Clearly describe your question.

## Context
- Environment: [DEV/TST/STG/PRD]
- Workflow/Action version: [e.g. v1.0.0]

## Additional Details
Add screenshots, logs, or workflow snippets if helpful.
