apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-config
  namespace: xlda-monitoring
data:
  prometheus.yml: |
    global:
      scrape_interval: 15s
      evaluation_interval: 15s
    rule_files:
      - /etc/prometheus/alert_rules/alert_rules.yml
    scrape_configs:
      - job_name: 'pushgateway'
        static_configs:
          - targets: ['pushgateway.xlda-monitoring.svc.cluster.local:9091']
