apiVersion: apps/v1
kind: Deployment
metadata:
  name: pushgateway
  namespace: xlda-monitoring
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pushgateway
  template:
    metadata:
      labels:
        app: pushgateway
    spec:
      containers:
        - name: pushgateway
          image: prom/pushgateway:latest
          ports:
            - containerPort: 9091
          args: ["--web.listen-address=:9091"]
---
apiVersion: v1
kind: Service
metadata:
  name: pushgateway
  namespace: xlda-monitoring
spec:
  selector:
    app: pushgateway
  ports:
    - name: http
      port: 9091
      targetPort: 9091
