name: Deploy Docs

on:
  push:
    branches:
      - main

jobs:
  deploy-docs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v6
        with:
          python-version: '3.x'

      - name: Install MkDocs and Material theme
        run: |
          pip install mkdocs mkdocs-material

      - name: Build and Deploy Docs
        run: |
          mkdocs gh-deploy --force
