name: Project Automation
permissions:
  issues: write
  pull-requests: write

on:
  issues:
    types: [opened, reopened, closed]
  pull_request:
    types: [opened, reopened, closed, merged]

jobs:
  project-automation:
    runs-on: ubuntu-latest
    steps:
      - name: Move issue/PR to project board
        uses: alex-page/github-project-automation-plus@v0.9.0
        with:
          project: "Deployment Pipeline"
          column: ${{ github.event.action == 'closed' && 'Done' || 'In Progress' }}
          repo-token: ${{ secrets.GITHUB_TOKEN }}
